### ISSUE TITLE
Detects sd card as system drive on 2-in-1 Convertable

### ISSUE THREAD

**Issue by BleedingEdgeTech** [resin-io/etcher#885]
- 1.0.0-beta. 16
- Windows 10 64-bit

I was chatting with @WasabiFan on resin-io/etcher
he sent me this skript
https://github.com/resin-io/etcher/issues/new 

output was:

```
PS C:\Users\agmai\Desktop\temp> .\Win32.bat
device: "\\\\.\\PHYSICALDRIVE0"
description: "SAMSUNG MZNLF128HCHP-000H1"
size: 128034708480
raw: "\\\\.\\PHYSICALDRIVE0"
system: True
protected: False
mountpoints:
  - path: "C:"

device: "\\\\.\\PHYSICALDRIVE1"
description: "Generic SA02G SD Card"
size: 1965841920
raw: "\\\\.\\PHYSICALDRIVE1"
system: True
protected: False
mountpoints:
  - path: "D:"

PS C:\Users\agmai\Desktop\temp>
```

D: is a 2GB SD card with no system files on them an was the drive i wanted to flash ev3dev onto

Thank you in advance.

ps.: i resolved my issue when i activated unsafe mode in the settings
